## TIL20220407

### 다중 그래프 in ggplot

[Use for loop to plot multiple lines in single plot with ggplot2](https://stackoverflow.com/questions/14704742/use-for-loop-to-plot-multiple-lines-in-single-plot-with-ggplot2)

```{r}
if(!require(ggplot2)) { install.packages("ggplot2"); library(ggplot2); }

y <- matrix(rnorm(100), 10, 10)
m <- qplot(NULL)
for(i in 1:10) {
    m <- m + geom_line(aes(x = 1:10, y = y[,i]))
}
plot(m)
```

```{r}
plot(1,1,type='n', ylim=range(y), xlim=c(1,10))
for(i in 1:10) {
    lines(1:10, y[,i])
}
```

```{r}
y <- matrix(rnorm(100), 10, 10)
if(!require(reshape2)) { install.packages("reshape2"); library(reshape2); }
y_m <- melt(y)

ggplot() +
  geom_line(data = y_m, aes(x = Var1, y = value, group = Var2))
```

```{r}
df <- NULL
for(i in 1:10){
 temp_df <- data.frame(x=1:10, y=y[,i], col=rep(i:i, each=10))
 df <- rbind(df,temp_df)
} 

ggplot(df,aes(x=x,y=y,group=col,colour=factor(col))) + 
  geom_smooth(method = "lm")
```

[How to create a plot using ggplot2 with Multiple Lines in R ?](https://www.geeksforgeeks.org/how-to-create-a-plot-using-ggplot2-with-multiple-lines-in-r/)

```{r}
gfg_data <- data.frame(x = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                   y1 = c(1.1, 2.4, 3.5, 4.1, 5.9, 6.7, 
                          7.1, 8.3, 9.4, 10.0),
                   y2 = c(7, 5, 1, 7, 4, 9, 2, 3, 1, 4),
                   y3 = c(5, 6, 4, 5, 1, 8, 7, 4, 5, 4),
                   y4 = c(1, 4, 8, 9, 6, 1, 1, 8, 9, 1),
                   y5 = c(1, 1, 1, 3, 3, 7, 7, 10, 10, 10))
```

```{r}
if(!require(reshape2)) { install.packages("reshape2"); library(reshape2); }

data.long <- melt(gfg_data, id = "x")
```

```{r}
gfg_plot <- ggplot(data.long,
                   aes(x = x,
                       y = value,
                       color = variable)) + 
  geom_point() +
  geom_smooth(level=0.3, method = "loess") +
  theme(legend.position = c(.3, .93), legend.direction = 'horizontal',
        legend.background = element_rect(fill = NA, color = NA),
        legend.key = element_rect(fill = "white", color = NA)); gfg_plot
```

