## TIL20220519

### 모델 만들기

```{r}
if(!require(tidyverse)) { install.packages("tidyverse"); library(tidyverse); }
if(!require(tidymodels)) { install.packages("tidymodels"); library(tidymodels); }
if(!require(tidytext)) { install.packages("tidytext"); library(tidytext); }
if(!require(skimr)) { install.packages("skimr"); library(skimr); }
if(!require(vip)) { install.packages("vip"); library(vip); }
```

```{r}
bank_tb <- read_csv("UniversalBank.csv", col_names = T,
                    locale = locale("ko", encoding = "euc-kr"),
                    na = ".") %>% 
  mutate_if(is.character, as.factor) 
str(bank_tb)
```

```{r}
head(bank_tb)
```

```{r}
# 변수명 점검
bank_tb <- bank_tb %>% 
  rename(c("Personal_Loan" = "Personal Loan",
           "CD_Account" = "CD Account",
           "Securities_Account" = "Securities Account"))
str(bank_tb)
```

```{r}
# 자료형 점검
bank_tb <- bank_tb %>% 
  mutate(Personal_Loan = factor(Personal_Loan,
                                levels = c(1, 0),
                                labels = c("Yes", "No"))) %>% 
  mutate(Securities_Account = factor(Securities_Account,
                                     levels = c(0,1),
                                     labels = c("No", "Yes"))) %>% 
  mutate(CD_Account = factor(CD_Account, 
                             levels = c(0,1),
                             labels = c("No", "Yes"))) %>% 
  mutate(Online = factor(Online, 
                         levels = c(0,1),
                         labels = c("No", "Yes"))) %>% 
  mutate(CreditCard = factor(CreditCard, 
                         levels = c(0,1),
                         labels = c("No", "Yes"))) %>%
  mutate(Education = factor(Education, 
                         levels = c(1:3),
                         labels = c("Undergrad", "Graduate", "Professonal")))
str(bank_tb)  
```

```{r}
# 변수 점검 (삭제, 변환 등)
bank_tb <- bank_tb %>% 
  select(-c(ID, 'ZIP Code'))
str(bank_tb)
```

```{r}
# EDA
skim(bank_tb)
```

```{r}
bank_tb %>% 
  group_by(Personal_Loan) %>% 
  skim()
```

```{r}
# base accuracy
bank_tb %>% 
  count(Personal_Loan) %>% 
  mutate(prop = n / sum(n))
```

```{r}
# 데이터셋 분할
set.seed(123)
bank_split <- bank_tb %>% 
  initial_split(strata = Personal_Loan)
bank_split

```

```{r}
train_data <- training(bank_split)
test_data <- testing(bank_split)
```


```{r}
args(decision_tree)
```

```{r}
# model
tree_model <- decision_tree() %>% 
  set_engine("rpart") %>% 
  set_mode("classification")
tree_model
```

```{r}
# recipe
tree_recipe <- train_data %>% 
  recipe(Personal_Loan ~ .) %>% 
  step_dummy(all_nominal(), -all_outcomes())
summary(tree_recipe)
```


```{r}
# workflow
tree_workflow <- workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(tree_recipe)
tree_workflow
```

```{r}
# fit
tree_train_fit <- tree_workflow %>% 
  fit(data = train_data)
tree_train_fit
```

```{r}
tree_train_pred <- predict(tree_train_fit,
                           train_data,
                           type = "prob") %>% 
  bind_cols(predict(tree_train_fit, train_data)) %>% 
  bind_cols(train_data %>% select(Personal_Loan))
```

```{r}
tree_train_conf <- tree_train_pred %>% 
  conf_mat(truth = Personal_Loan, estimate = .pred_class)
```

```{r}
autoplot(tree_train_conf, type = "heatmap")
```

```{r}
autoplot(tree_train_conf, type = "mosaic")
```

```{r}
summary(tree_train_conf)
```

```{r}
tree_train_pred %>% 
  roc_auc(truth = Personal_Loan, .pred_Yes)
```

```{r}
train_auc <- tree_train_pred %>% 
  roc_curve(truth = Personal_Loan, estimate = .pred_Yes) %>% 
  mutate(model = "train_auc")
```

```{r}
autoplot(train_auc)
```



```{r}
tree_train_pred %>% 
  lift_curve(truth = Personal_Loan, estimate = .pred_Yes) %>% 
  autoplot()
```

```{r}
tree_train_pred %>% 
  gain_curve(truth = Personal_Loan, estimate = .pred_Yes) %>% 
  autoplot()
```

```{r}
tree_train_fit %>% 
  pull_workflow_fit() %>% 
  vip()
```

```{r}
tree_test_fit <- 
  tree_workflow %>% 
  last_fit(bank_split)
tree_test_fit
```

```{r}
tree_test_fit$.predictions
```

```{r}
tree_test_pred <- 
  tree_test_fit %>% 
  collect_predictions()
```

```{r}
tree_test_conf <- 
  tree_test_pred %>% 
  conf_mat(truth = Personal_Loan,
           estimate = .pred_class)
tree_test_conf
```

```{r}
tree_test_conf %>% autoplot(type = "heatmap")
```

```{r}
summary(tree_test_conf)
```


```{r}
tree_test_pred %>% 
  roc_auc(truth = Personal_Loan, estimate = .pred_Yes)
```

```{r}
test_auc <- tree_test_pred %>% 
  roc_curve(truth = Personal_Loan, estimate = .pred_Yes) %>% 
  mutate(model = "test_auc")
autoplot(test_auc)
```

```{r}
tree_test_pred %>% 
  lift_curve(truth = Personal_Loan, estimate = .pred_Yes) %>% 
  autoplot()
```

```{r}
tree_test_pred %>% 
  gain_curve(truth = Personal_Loan, estimate = .pred_Yes) %>% 
  autoplot()
```

```{r}
tree_test_fit %>% 
  pluck(".workflow", 1) %>% 
  pull_workflow_fit() %>% 
  vip(num_features = 20)
```

```{r}
tree_train_conf
```

```{r}
tree_test_conf
```

```{r}
summary(tree_train_conf)
```

```{r}
summary(tree_test_conf)
```

```{r}
bind_rows(train_auc, test_auc) %>% 
  ggplot(mapping = aes(x = 1-specificity,
                       y = sensitivity,
                       color = model)) +
  geom_path(lwd = 1.5) +
  geom_abline(lty = 3) +
  coord_equal()
```

```{r}
if(!require(rpart.plot)) { install.packages("rpart.plot"); library(rpart.plot); }
rpart_fit <- tree_train_fit %>% 
  pull_workflow_fit()
```

```{r}
rpart.plot(x = rpart_fit$fit,
           yesno = 2, type = 2, extra = 1, split.font = 1, varlen = -10)
```

```{r}
prp(x = rpart_fit$fit, 
    type = 1, 
    extra = 1, 
    under = T, 
    split.font = 1, 
    varlen = -10,
    box.col = ifelse(rpart_fit$fit$frame$var == "<leaf>", "gray", "white")
)
```

