# 2022년 3월 

## TIL20220302

### 데이터 요약

#### 범주형 변수 요약

##### 비율 계산

```{r}
if(require(MASS)) install.packages("MASS")
library(MASS)

survey$Smoke=="Never" # 비흡연자에 대한 논리연산
mean(survey$Smoke=="Never", na.rm = T) # 비흡연자에 대한 비율
```

```{r}
head(anorexia)
```

```{r}
anorexia$Postwt > anorexia$Prewt # 치료 후의 몸무게가 치료 전의 몸무게보다 큰가?
mean(anorexia$Postwt > anorexia$Prewt)
```

```{r}
head(mammals)
```

```{r}
# 두뇌의 무게가 2개의 표준편차보다 큰 논리연산식
abs(mammals$brain - mean(mammals$brain)) > 2*sd(mammals$brain)
```

```{r}
mean(abs(mammals$brain - mean(mammals$brain)) > 2*sd(mammals$brain))
```

```{r}
head(SP500)
```

```{r}
# 수익률이 전일보다 증가한 일자 논리식
head(diff(SP500) > 0, 10)
```

```{r}
mean(diff(SP500) > 0)
```

```{r}
if(require(vcd)) install.packages("vcd")
library(vcd)

str(Arthritis)
```


## TIL20220301

### 데이터 요약

#### 범주형 변수 요약

기술통계와 추론통계, 대부분은 모집단을 설명하는 추론통계이지만 모집단을 잘 설명하기 위해서는 표본집단을 잘 이해사고 적절한 통계기법을 선택하는 것이 중요하다.  

##### 빈도표

```{r}
if(require(MASS)) install.packages("MASS")
library(MASS)

str(survey)
```

```{r}
levels(survey$Smoke)
```

```{r}
frqtab <- table(survey$Smoke)
frqtab
```

```{r}
class(frqtab)
```

```{r}
frqtab[2]
```

```{r}
frqtab["Never"]
```

##### 최빈값

```{r}
frqtab == max(frqtab)
```

```{r}
frqtab[frqtab == max(frqtab)]
```

```{r}
names(frqtab[frqtab == max(frqtab)])
```

```{r}
which.max(frqtab)
```

```{r}
frqtab[which.max(frqtab)]
```

```{r}
names(frqtab[which.max(frqtab)])
```

##### 비율도표

```{r}
frqtab.prop <- prop.table(frqtab)
frqtab.prop
```

```{r}
frqtab.prop["Never"]
```

```{r}
frqtab.prop * 100
```

